### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by AntonSchnfeld** [UniCode9696/My-lifes-work#1]
There is a spelling mistake in My-lifes-work/Projects/Ideas.txt on line 1:
„ In this file you'll find all of my coding (and mabye other)[…]“
You wrote „mabye“, but I think you meant to write „maybe“.

**Comment by UniCode9696** [comment]
Fixed

**Comment by AntonSchnfeld** [comment]
Another grammar mistake in „What is this.txt“ on line 4 „[…] rightaway helpful […]“.

**Comment by AntonSchnfeld** [comment]
Another grammar issue in „What is this.txt?“ on line 8 „[…] though still so much more […]“.

**Comment by AntonSchnfeld** [comment]
Another grammar issue in „What is this.txt?“ on line 9 „[…] because I can articulate myself way more accurate then[…]“.

**Comment by AntonSchnfeld** [comment]
Another grammar issue in „What is this.txt?“ on line 14 „[…] that (without already diving too deep into one of the topics), if I die I feel like[…]“.

**Comment by AntonSchnfeld** [comment]
Thanks for fixing the grammar :)
